/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/roboops/2014Software/groovy2014/src/Messages/msg/ArmStatusMessage.msg
 *
 */


#ifndef MESSAGES_MESSAGE_ARMSTATUSMESSAGE_H
#define MESSAGES_MESSAGE_ARMSTATUSMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Messages
{
template <class ContainerAllocator>
struct ArmStatusMessage_
{
  typedef ArmStatusMessage_<ContainerAllocator> Type;

  ArmStatusMessage_()
    : boomCurrent(0)
    , armRotCurrent(0)
    , thumbPosition(0)
    , clawPosition(0)
    , stickPosition(0)
    , boomPosition(0)
    , armRotPosition(0)
    , panPosition(0)
    , tiltPosition(0)  {
    }
  ArmStatusMessage_(const ContainerAllocator& _alloc)
    : boomCurrent(0)
    , armRotCurrent(0)
    , thumbPosition(0)
    , clawPosition(0)
    , stickPosition(0)
    , boomPosition(0)
    , armRotPosition(0)
    , panPosition(0)
    , tiltPosition(0)  {
    }



   typedef int32_t _boomCurrent_type;
  _boomCurrent_type boomCurrent;

   typedef int32_t _armRotCurrent_type;
  _armRotCurrent_type armRotCurrent;

   typedef int32_t _thumbPosition_type;
  _thumbPosition_type thumbPosition;

   typedef int32_t _clawPosition_type;
  _clawPosition_type clawPosition;

   typedef int32_t _stickPosition_type;
  _stickPosition_type stickPosition;

   typedef int32_t _boomPosition_type;
  _boomPosition_type boomPosition;

   typedef int32_t _armRotPosition_type;
  _armRotPosition_type armRotPosition;

   typedef int32_t _panPosition_type;
  _panPosition_type panPosition;

   typedef int32_t _tiltPosition_type;
  _tiltPosition_type tiltPosition;




  typedef boost::shared_ptr< ::Messages::ArmStatusMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Messages::ArmStatusMessage_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ArmStatusMessage_

typedef ::Messages::ArmStatusMessage_<std::allocator<void> > ArmStatusMessage;

typedef boost::shared_ptr< ::Messages::ArmStatusMessage > ArmStatusMessagePtr;
typedef boost::shared_ptr< ::Messages::ArmStatusMessage const> ArmStatusMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Messages::ArmStatusMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Messages::ArmStatusMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg'], 'Messages': ['/home/roboops/2014Software/groovy2014/src/Messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Messages::ArmStatusMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Messages::ArmStatusMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Messages::ArmStatusMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Messages::ArmStatusMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Messages::ArmStatusMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Messages::ArmStatusMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Messages::ArmStatusMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39dd7004df49d35f5a38291f8b4a5676";
  }

  static const char* value(const ::Messages::ArmStatusMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39dd7004df49d35fULL;
  static const uint64_t static_value2 = 0x5a38291f8b4a5676ULL;
};

template<class ContainerAllocator>
struct DataType< ::Messages::ArmStatusMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Messages/ArmStatusMessage";
  }

  static const char* value(const ::Messages::ArmStatusMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Messages::ArmStatusMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 boomCurrent\n\
int32 armRotCurrent\n\
int32 thumbPosition\n\
int32 clawPosition\n\
int32 stickPosition\n\
int32 boomPosition\n\
int32 armRotPosition\n\
int32 panPosition\n\
int32 tiltPosition\n\
";
  }

  static const char* value(const ::Messages::ArmStatusMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Messages::ArmStatusMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.boomCurrent);
      stream.next(m.armRotCurrent);
      stream.next(m.thumbPosition);
      stream.next(m.clawPosition);
      stream.next(m.stickPosition);
      stream.next(m.boomPosition);
      stream.next(m.armRotPosition);
      stream.next(m.panPosition);
      stream.next(m.tiltPosition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ArmStatusMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Messages::ArmStatusMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Messages::ArmStatusMessage_<ContainerAllocator>& v)
  {
    s << indent << "boomCurrent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.boomCurrent);
    s << indent << "armRotCurrent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.armRotCurrent);
    s << indent << "thumbPosition: ";
    Printer<int32_t>::stream(s, indent + "  ", v.thumbPosition);
    s << indent << "clawPosition: ";
    Printer<int32_t>::stream(s, indent + "  ", v.clawPosition);
    s << indent << "stickPosition: ";
    Printer<int32_t>::stream(s, indent + "  ", v.stickPosition);
    s << indent << "boomPosition: ";
    Printer<int32_t>::stream(s, indent + "  ", v.boomPosition);
    s << indent << "armRotPosition: ";
    Printer<int32_t>::stream(s, indent + "  ", v.armRotPosition);
    s << indent << "panPosition: ";
    Printer<int32_t>::stream(s, indent + "  ", v.panPosition);
    s << indent << "tiltPosition: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tiltPosition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_ARMSTATUSMESSAGE_H
