/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/roboops/2014Software/groovy2014/src/Messages/msg/DriveTrainStatusMessage.msg
 *
 */


#ifndef MESSAGES_MESSAGE_DRIVETRAINSTATUSMESSAGE_H
#define MESSAGES_MESSAGE_DRIVETRAINSTATUSMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Messages
{
template <class ContainerAllocator>
struct DriveTrainStatusMessage_
{
  typedef DriveTrainStatusMessage_<ContainerAllocator> Type;

  DriveTrainStatusMessage_()
    : BLCurrent(0)
    , FLCurrent(0)
    , BRCurrent(0)
    , FRCurrent(0)
    , BLVelocity(0)
    , FLVelocity(0)
    , BRVelocity(0)
    , FRVelocity(0)
    , Voltage1(0)  {
    }
  DriveTrainStatusMessage_(const ContainerAllocator& _alloc)
    : BLCurrent(0)
    , FLCurrent(0)
    , BRCurrent(0)
    , FRCurrent(0)
    , BLVelocity(0)
    , FLVelocity(0)
    , BRVelocity(0)
    , FRVelocity(0)
    , Voltage1(0)  {
    }



   typedef int32_t _BLCurrent_type;
  _BLCurrent_type BLCurrent;

   typedef int32_t _FLCurrent_type;
  _FLCurrent_type FLCurrent;

   typedef int32_t _BRCurrent_type;
  _BRCurrent_type BRCurrent;

   typedef int32_t _FRCurrent_type;
  _FRCurrent_type FRCurrent;

   typedef int32_t _BLVelocity_type;
  _BLVelocity_type BLVelocity;

   typedef int32_t _FLVelocity_type;
  _FLVelocity_type FLVelocity;

   typedef int32_t _BRVelocity_type;
  _BRVelocity_type BRVelocity;

   typedef int32_t _FRVelocity_type;
  _FRVelocity_type FRVelocity;

   typedef int32_t _Voltage1_type;
  _Voltage1_type Voltage1;




  typedef boost::shared_ptr< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct DriveTrainStatusMessage_

typedef ::Messages::DriveTrainStatusMessage_<std::allocator<void> > DriveTrainStatusMessage;

typedef boost::shared_ptr< ::Messages::DriveTrainStatusMessage > DriveTrainStatusMessagePtr;
typedef boost::shared_ptr< ::Messages::DriveTrainStatusMessage const> DriveTrainStatusMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Messages::DriveTrainStatusMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg'], 'Messages': ['/home/roboops/2014Software/groovy2014/src/Messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1afd2d5a92d4dbd48c700a5e7e6912c";
  }

  static const char* value(const ::Messages::DriveTrainStatusMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1afd2d5a92d4dbdULL;
  static const uint64_t static_value2 = 0x48c700a5e7e6912cULL;
};

template<class ContainerAllocator>
struct DataType< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Messages/DriveTrainStatusMessage";
  }

  static const char* value(const ::Messages::DriveTrainStatusMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 BLCurrent\n\
int32 FLCurrent\n\
int32 BRCurrent\n\
int32 FRCurrent\n\
int32 BLVelocity\n\
int32 FLVelocity\n\
int32 BRVelocity\n\
int32 FRVelocity\n\
int32 Voltage1\n\
";
  }

  static const char* value(const ::Messages::DriveTrainStatusMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BLCurrent);
      stream.next(m.FLCurrent);
      stream.next(m.BRCurrent);
      stream.next(m.FRCurrent);
      stream.next(m.BLVelocity);
      stream.next(m.FLVelocity);
      stream.next(m.BRVelocity);
      stream.next(m.FRVelocity);
      stream.next(m.Voltage1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DriveTrainStatusMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Messages::DriveTrainStatusMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Messages::DriveTrainStatusMessage_<ContainerAllocator>& v)
  {
    s << indent << "BLCurrent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.BLCurrent);
    s << indent << "FLCurrent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.FLCurrent);
    s << indent << "BRCurrent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.BRCurrent);
    s << indent << "FRCurrent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.FRCurrent);
    s << indent << "BLVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.BLVelocity);
    s << indent << "FLVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.FLVelocity);
    s << indent << "BRVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.BRVelocity);
    s << indent << "FRVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.FRVelocity);
    s << indent << "Voltage1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Voltage1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_DRIVETRAINSTATUSMESSAGE_H
