/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/roboops/2014Software/groovy2014/src/Messages/msg/GPSMessage.msg
 *
 */


#ifndef MESSAGES_MESSAGE_GPSMESSAGE_H
#define MESSAGES_MESSAGE_GPSMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Messages
{
template <class ContainerAllocator>
struct GPSMessage_
{
  typedef GPSMessage_<ContainerAllocator> Type;

  GPSMessage_()
    : roll(0)
    , pitch(0)
    , yaw(0)
    , latitude(0)
    , longitude(0)
    , satilites(0)  {
    }
  GPSMessage_(const ContainerAllocator& _alloc)
    : roll(0)
    , pitch(0)
    , yaw(0)
    , latitude(0)
    , longitude(0)
    , satilites(0)  {
    }



   typedef int32_t _roll_type;
  _roll_type roll;

   typedef int32_t _pitch_type;
  _pitch_type pitch;

   typedef int32_t _yaw_type;
  _yaw_type yaw;

   typedef int32_t _latitude_type;
  _latitude_type latitude;

   typedef int32_t _longitude_type;
  _longitude_type longitude;

   typedef int32_t _satilites_type;
  _satilites_type satilites;




  typedef boost::shared_ptr< ::Messages::GPSMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Messages::GPSMessage_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GPSMessage_

typedef ::Messages::GPSMessage_<std::allocator<void> > GPSMessage;

typedef boost::shared_ptr< ::Messages::GPSMessage > GPSMessagePtr;
typedef boost::shared_ptr< ::Messages::GPSMessage const> GPSMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Messages::GPSMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Messages::GPSMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg'], 'Messages': ['/home/roboops/2014Software/groovy2014/src/Messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Messages::GPSMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Messages::GPSMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Messages::GPSMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Messages::GPSMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Messages::GPSMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Messages::GPSMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Messages::GPSMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e4e1b9d0d3c96c446e9fa061792baf8";
  }

  static const char* value(const ::Messages::GPSMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e4e1b9d0d3c96c4ULL;
  static const uint64_t static_value2 = 0x46e9fa061792baf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::Messages::GPSMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Messages/GPSMessage";
  }

  static const char* value(const ::Messages::GPSMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Messages::GPSMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 roll\n\
int32 pitch\n\
int32 yaw\n\
int32 latitude\n\
int32 longitude\n\
int32 satilites\n\
";
  }

  static const char* value(const ::Messages::GPSMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Messages::GPSMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.satilites);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GPSMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Messages::GPSMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Messages::GPSMessage_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<int32_t>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yaw);
    s << indent << "latitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.longitude);
    s << indent << "satilites: ";
    Printer<int32_t>::stream(s, indent + "  ", v.satilites);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_GPSMESSAGE_H
